apiVersion: v1
kind: ResourceQuota
metadata:
  name: cpu-mem-quota
spec:
  hard:
    limits.cpu: "4"
    limits.memory: "8Gi"
    pods: "10"
    replicationcontrollers: "4"
    requests.cpu: "2"
    requests.memory: "4Gi"
    services: "5"
